services:

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tuhamworld/portfolio-backend:1.0
    container_name: express-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "80"
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    image: tuhamworld/portfolio-frontend:1.0
    container_name: react-frontend
    restart: always
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: